### ISSUE TITLE
net-libs/webkit-gtk-2.8.1: build fails due to wrong linker flag

### ISSUE THREAD

**Issue by oleid** [Flex1911/qwin-overlay#2]
Hey,

build fails on my machine as ld.gold doesn't support "--reduce-memory-overheads" flag. I'm using the default bfd linker. It seems as if gold is automatically used when available[1], however if it's not default, the faulty flag gets applied in the ebuild:

```
159:    if ! $(tc-getLD) --version | grep -q "GNU gold"; then
160-            append-ldflags "-Wl,--reduce-memory-overheads"
161-    fi
```

As soon as I switch the default linker to gold, the build seems to work just fine (still running).

[1] happend on my machine and https://code.google.com/p/chromium/issues/detail?id=360082#c12 claims it, too. It's for chromium, but I guess that's not too different.

**Comment by Flex1911** [comment]
Yeah,i know that bug. I'll fix it now.

**Comment by oleid** [comment]
Thanks a lot!

**Comment by Flex1911** [comment]
I've disabled that flag for now,webkit now compiling on my machine without errors.

**Comment by Flex1911** [comment]
Always happy to help.

**Comment by Flex1911** [comment]
Fixed for now

**Comment by oleid** [comment]
seems to work here, too! :)
